// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hearthStoneDeckBuilder.Models;

namespace hearthStoneDeckBuilder.Migrations
{
    [DbContext(typeof(HSContext))]
    partial class HSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("hearthStoneDeckBuilder.Models.Card", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CardClass");

                    b.Property<int>("Cost");

                    b.Property<string>("LinkPicture");

                    b.Property<string>("Name");

                    b.Property<int>("Rarity");

                    b.Property<string>("Text");

                    b.Property<int>("Type");

                    b.Property<int>("deckID");

                    b.HasKey("ID");

                    b.HasIndex("deckID");

                    b.ToTable("Card");
                });

            modelBuilder.Entity("hearthStoneDeckBuilder.Models.Deck", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author")
                        .IsRequired();

                    b.Property<int>("ClassType");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Deck");
                });

            modelBuilder.Entity("hearthStoneDeckBuilder.Models.Card", b =>
                {
                    b.HasOne("hearthStoneDeckBuilder.Models.Deck")
                        .WithMany("List")
                        .HasForeignKey("deckID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
